---
title: "Assignment 11"
author: "Daehee Cho"
date: "`r Sys.Date()`"
output: flexdashboard::flex_dashboard
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
library(crosstalk)
```

```{r}
pokemon <- read_csv("pokemon.csv")
```

```{r}
shared_pokemon <- SharedData$new(pokemon)
```

Column
-------------------------------------

### Distribution of Total Stats by Primary Type

```{r, echo = FALSE}
pokemon <- pokemon %>%
  mutate(`Type 1` = fct_reorder(`Type 1`, Total, .fun = median, .desc = TRUE))

shared_pokemon <- SharedData$new(pokemon)

boxplot <- shared_pokemon %>%
  ggplot(aes(x = `Type 1`, y = Total, fill = `Type 1`)) +
  geom_boxplot(outlier.size = 1, outlier.shape = 21) +
  labs(
    x = "Primary Type",
    y = "Total Stats"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplotly(boxplot)

```

Column
-------------------------------------

### Attack vs. Defense Scatter Plot

```{r, echo = FALSE}
p <- shared_pokemon %>%
  ggplot(aes(x = Defense, y = Attack, color = `Type 1`)) +
  geom_point(size = 2, alpha = 0.7) +
  labs(
    title = "Attack vs Defense Scatter Plot",
    x = "Defense",
    y = "Attack",
    color = "Primary Type"
  ) +
  theme_minimal()
ggplotly(p)
```

SidebarName {.sidebar}
----------------------

```{r, echo = FALSE}
filter_select("poke_type", "Pokemon Type", shared_pokemon, ~`Type 1`)
```



